### PR TITLE
Use the new `env_filter` instead of `env_logger`

### PR DESCRIPTION
**Pull request by kayabaNerve**

### CODE REVIEW

**Review by bnjbvr — CHANGES_REQUESTED** [review]
Thanks, but it's not the right way: we should probably replace `env_logger` with `env_filter` and use that, instead of creating a new logger that's only used for its filter.

**Comment by kayabaNerve** [comment]
Ah. That's the distinction. Sorry, missed that while trying to get a quick patch out.

**Comment by kayabaNerve** [comment]
Rewrote to env_filter.

**Review by bnjbvr — APPROVED** [review]
Very nice, it does lower the size of the Cargo.lock file. Maybe that warrants a new patch release...

**Comment by kayabaNerve** [comment]
Probably a minor?

**Pull request merged**
